name: "selftesting"
on:
  issue_comment:
    types: created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
        no-color: true
        yes: true
    - name: Install Dependencies
      run: sudo apt-get install --no-install-recommends -yq valgrind tree
    - uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
