name: "selftesting"
on:
  issue_comment:
    types: created

jobs:
  linux_bisects:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
        no-color: true
        yes: true
    - name: linux_bisects
      shell: bash
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  mac_bisects:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
        no-color: true
        yes: true
    - name: mac_bisects
      shell: bash
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  windows_bisects:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
        no-color: true
        yes: true
    - name: mac_bisects
      shell: bash
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
