name: "selftesting"
on:
  issue_comment:
    types: created

jobs:
  bisects:
    if: |
      github.event_name == 'issue_comment'
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    name: ${{ matrix.platform }}-bisects
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'devel'
          no-color: true
          yes: true
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
